name: admin_colorblindtest
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  fluttertoast: ^8.2.2
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  image_cropper: ^5.0.0
  image_picker: ^1.0.2
  font_awesome_flutter: ^10.1.0
  firebase_storage: ^11.2.5
  googleapis_auth: ^1.4.1
  gcloud: ^0.8.11
  typed_data: ^1.3.2
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  background_image: "images/logo.PNG"

flutter:


  uses-material-design: true


  assets:
    - images/
    - assets/
  #   - images/a_dot_ham.jpeg

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 